"""
Export trained Decision Tree model to C/C++ code for Arduino/ESP32 deployment
"""

import joblib
import argparse
from sklearn.tree import DecisionTreeRegressor
import numpy as np


def tree_to_code(tree, feature_names):
    """
    Convert scikit-learn Decision Tree to C/C++ code
    
    Args:
        tree: Trained DecisionTreeRegressor
        feature_names: List of feature names
        
    Returns:
        str: C/C++ code
    """
    tree_ = tree.tree_
    feature_name = [
        feature_names[i] if i != -2 else "undefined!"
        for i in tree_.feature
    ]
    
    def recurse(node, depth):
        indent = "  " * depth
        if tree_.feature[node] != -2:  # Not a leaf node
            name = feature_name[node]
            threshold = tree_.threshold[node]
            
            code = f"{indent}if ({name} <= {threshold:.6f}f) {{\n"
            code += recurse(tree_.children_left[node], depth + 1)
            code += f"{indent}}} else {{\n"
            code += recurse(tree_.children_right[node], depth + 1)
            code += f"{indent}}}\n"
            return code
        else:  # Leaf node
            value = tree_.value[node][0][0]
            return f"{indent}return {value:.6f}f;\n"
    
    code = "float predict_brightness(float ambient_light, int motion_detected, float sin_hour, float cos_hour, int time_period, int day_of_week) {\n"
    code += recurse(0, 1)
    code += "}\n"
    
    return code


def export_model_to_arduino(model_path, output_path):
    """
    Export model to Arduino-compatible C header file
    
    Args:
        model_path (str): Path to trained model (.pkl)
        output_path (str): Output path for C header file
    """
    print(f"Loading model from {model_path}...")
    
    # Load model
    model_data = joblib.load(model_path)
    model = model_data['model']
    feature_columns = model_data['feature_columns']
    
    print(f"Model loaded. Tree depth: {model.get_depth()}")
    print(f"Number of leaves: {model.get_n_leaves()}")
    print(f"Features: {feature_columns}")
    
    # Convert to C code
    print("\nConverting to C/C++ code...")
    c_code = tree_to_code(model, feature_columns)
    
    # Generate header file
    header_content = f"""/*
 * Auto-generated Decision Tree for LED Brightness Control
 * Generated from trained scikit-learn model
 * 
 * Tree Statistics:
 *   - Depth: {model.get_depth()}
 *   - Leaves: {model.get_n_leaves()}
 *   - Features: {', '.join(feature_columns)}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 */

#ifndef TREE_RULES_H
#define TREE_RULES_H

/*
 * Predict LED brightness based on sensor inputs and time features
 * 
 * Parameters:
 *   ambient_light: Ambient light level from LDR (lux, typically 0-1000)
 *   motion_detected: Motion detection from PIR (0 or 1)
 *   sin_hour: Sine component of hour (sin(2*PI*hour/24))
 *   cos_hour: Cosine component of hour (cos(2*PI*hour/24))
 *   time_period: Time period code (0=Early Morning, 1=Morning, 2=Afternoon, 3=Evening, 4=Night)
 *   day_of_week: Day of week (0=Monday, 1=Tuesday, ..., 6=Sunday)
 * 
 * Returns:
 *   Predicted LED brightness (0-100%)
 */
{c_code}

#endif // TREE_RULES_H
"""
    
    # Write to file
    with open(output_path, 'w') as f:
        f.write(header_content)
    
    print(f"\n✓ Model exported to {output_path}")
    print(f"\nFile size: {len(header_content)} bytes")
    print("\nNext steps:")
    print("1. Copy this file to your Arduino sketch folder")
    print("2. Include it in your sketch: #include \"tree_rules.h\"")
    print("3. Call predict_brightness() with sensor inputs")
    
    # Generate statistics
    print("\n" + "="*70)
    print("DEPLOYMENT STATISTICS")
    print("="*70)
    
    # Estimate memory usage
    num_nodes = model.tree_.node_count
    approx_memory = num_nodes * 16  # Rough estimate: 16 bytes per node
    
    print(f"Estimated program memory: ~{len(c_code)} bytes (code)")
    print(f"Estimated RAM usage: minimal (only variables during prediction)")
    print(f"\nNumber of tree nodes: {num_nodes}")
    print(f"Number of comparisons (worst case): {model.get_depth()}")
    print(f"\nThis should work on:")
    print("  ✓ Arduino Uno (32 KB flash, 2 KB RAM)")
    print("  ✓ Arduino Mega (256 KB flash, 8 KB RAM)")
    print("  ✓ ESP32 (4 MB flash, 520 KB RAM)")
    print("  ✓ ESP8266 (4 MB flash, 80 KB RAM)")
    
    if model.get_depth() > 15:
        print("\n⚠️  Warning: Tree depth > 15 may cause stack overflow on limited devices")
        print("   Consider retraining with max_depth parameter limited to 10-12")


def export_test_data(model_path, output_path, num_samples=10):
    """
    Export test cases for validation on Arduino
    
    Args:
        model_path (str): Path to trained model
        output_path (str): Output path for test data
        num_samples (int): Number of test samples
    """
    print(f"\nGenerating {num_samples} test samples...")
    
    model_data = joblib.load(model_path)
    model = model_data['model']
    
    test_cases = []
    
    # Generate diverse test cases
    scenarios = [
        {'ambient': 50, 'motion': 1, 'hour': 22, 'period': 4, 'day': 1},    # Night, low light, motion, Tuesday
        {'ambient': 800, 'motion': 1, 'hour': 22, 'period': 4, 'day': 1},   # Night, HIGH light, motion, Tuesday (NEW RULE)
        {'ambient': 800, 'motion': 0, 'hour': 22, 'period': 4, 'day': 1},   # Night, HIGH light, NO motion, Tuesday (NEW RULE)
        {'ambient': 400, 'motion': 1, 'hour': 8, 'period': 1, 'day': 2},    # Morning, medium light, Wednesday
        {'ambient': 900, 'motion': 0, 'hour': 14, 'period': 2, 'day': 3},   # Afternoon, high light, no motion, Thursday
        {'ambient': 200, 'motion': 1, 'hour': 18, 'period': 3, 'day': 4},   # Evening, low light, motion, Friday
        {'ambient': 30, 'motion': 0, 'hour': 5, 'period': 0, 'day': 0},     # Early morning, very low light, Monday
        {'ambient': 600, 'motion': 1, 'hour': 10, 'period': 1, 'day': 5},   # Morning, bright, Saturday
        {'ambient': 100, 'motion': 0, 'hour': 23, 'period': 4, 'day': 6},   # Late night, no motion, Sunday
        {'ambient': 500, 'motion': 1, 'hour': 16, 'period': 2, 'day': 0},   # Late afternoon, Monday
    ]
    
    for scenario in scenarios:
        hour = scenario['hour']
        sin_hour = np.sin(2 * np.pi * hour / 24)
        cos_hour = np.cos(2 * np.pi * hour / 24)
        
        # Predict
        import pandas as pd
        input_data = pd.DataFrame([{
            'ambient_light': scenario['ambient'],
            'motion_detected': scenario['motion'],
            'sin_hour': sin_hour,
            'cos_hour': cos_hour,
            'time_period': scenario['period'],
            'day_of_week': scenario['day']
        }])
        
        prediction = model.predict(input_data)[0]
        
        test_cases.append({
            'ambient_light': scenario['ambient'],
            'motion_detected': scenario['motion'],
            'sin_hour': sin_hour,
            'cos_hour': cos_hour,
            'time_period': scenario['period'],
            'day_of_week': scenario['day'],
            'hour': hour,
            'expected_brightness': prediction
        })
    
    # Write test data as C array
    c_test_code = """/*
 * Test cases for validating Decision Tree implementation
 * Compare Arduino predictions with these expected values
 */

#ifndef TEST_CASES_H
#define TEST_CASES_H

struct TestCase {
  float ambient_light;
  int motion_detected;
  float sin_hour;
  float cos_hour;
  int time_period;
  int day_of_week;
  int hour;
  float expected_brightness;
};

const int NUM_TEST_CASES = """ + str(len(test_cases)) + """;

const TestCase TEST_CASES[] = {
"""
    
    for tc in test_cases:
        c_test_code += f"  {{{tc['ambient_light']:.2f}f, {tc['motion_detected']}, "
        c_test_code += f"{tc['sin_hour']:.6f}f, {tc['cos_hour']:.6f}f, {tc['time_period']}, "
        c_test_code += f"{tc['day_of_week']}, {tc['hour']}, {tc['expected_brightness']:.6f}f}},\n"
    
    c_test_code += """};

/*
 * Validation function for Arduino
 * Call this in setup() to verify the model works correctly
 */
void validate_model() {
  Serial.println(F("=== Model Validation ==="));
  float max_error = 0.0f;
  int failures = 0;
  
  const char* day_names[] = {"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"};
  
  for (int i = 0; i < NUM_TEST_CASES; i++) {
    TestCase tc = TEST_CASES[i];
    float predicted = predict_brightness(
      tc.ambient_light,
      tc.motion_detected,
      tc.sin_hour,
      tc.cos_hour,
      tc.time_period,
      tc.day_of_week
    );
    
    float error = abs(predicted - tc.expected_brightness);
    if (error > max_error) max_error = error;
    if (error > 0.1) failures++;  // Allow small floating-point differences
    
    Serial.print(F("Test "));
    Serial.print(i + 1);
    Serial.print(F(": "));
    Serial.print(day_names[tc.day_of_week]);
    Serial.print(F(" "));
    Serial.print(tc.hour);
    Serial.print(F("h Exp="));
    Serial.print(tc.expected_brightness, 2);
    Serial.print(F("% Pred="));
    Serial.print(predicted, 2);
    Serial.print(F("% Err="));
    Serial.print(error, 4);
    Serial.println(error < 0.1 ? F(" PASS") : F(" FAIL"));
  }
  
  Serial.println(F("=== Validation Summary ==="));
  Serial.print(F("Tests: "));
  Serial.println(NUM_TEST_CASES);
  Serial.print(F("Failures: "));
  Serial.println(failures);
  Serial.print(F("Max Error: "));
  Serial.print(max_error, 4);
  Serial.println(F("%"));
  Serial.println(failures == 0 ? F("ALL TESTS PASSED") : F("SOME TESTS FAILED"));
  Serial.println();
}

#endif // TEST_CASES_H
"""
    
    with open(output_path, 'w') as f:
        f.write(c_test_code)
    
    print(f"✓ Test cases exported to {output_path}")
    print(f"   Use validate_model() in Arduino setup() to verify implementation")


def main():
    parser = argparse.ArgumentParser(
        description='Export Decision Tree model to Arduino C/C++ code'
    )
    parser.add_argument(
        '--model',
        type=str,
        required=True,
        help='Path to trained model (.pkl file)'
    )
    parser.add_argument(
        '--output',
        type=str,
        default='tree_rules.h',
        help='Output header file path (default: tree_rules.h)'
    )
    parser.add_argument(
        '--test-output',
        type=str,
        default='test_cases.h',
        help='Output test cases file path (default: test_cases.h)'
    )
    
    args = parser.parse_args()
    
    print("="*70)
    print("Decision Tree to Arduino Exporter")
    print("="*70 + "\n")
    
    # Export model
    export_model_to_arduino(args.model, args.output)
    
    # Export test cases
    export_test_data(args.model, args.test_output)
    
    print("\n" + "="*70)
    print("EXPORT COMPLETE!")
    print("="*70)
    print(f"\nGenerated files:")
    print(f"  - {args.output} (decision tree code)")
    print(f"  - {args.test_output} (validation tests)")


if __name__ == "__main__":
    main()
